import React from 'react';
import logo from './logo.svg';
import './App.css';

function App() {
  return (
    <div className="container">
      <div className="column">

        abc
      </div>
      <div className="column">
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
        fdndk<br />
      </div>
    </div>
  );
}

export default App;
